authors = ["William Herrera <wherrera@alahonua.com>"]
name = "EDFPlus"
uuid = "582d7a84-78fd-59ab-a7bb-47fc6b175004"
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.5, 1.6, 1.7, 1.8. 1.9"
DSP = "0.5, 0.6, 0.7, 0.8, 0.9"
IterTools = "1.2, 1.3, 1.4, 1.5, 1.6"

[targets]
test = ["Pkg", "Test"]
